import type {Metadata} from "next";
import React, {Suspense} from 'react';
import "./globals.css";
import {Loading} from "@/app/(components)/loading/loading";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Suspense fallback={<Loading/>}>
            {children}
        </Suspense>
        </body>
        </html>
    );
}
